### ISSUE TITLE
.

### ISSUE THREAD

**Issue by cyolc932** [i-abc/blog-friends#29]

**Comment by cyolc932** [comment]
老哥 您方便提交一下我的友链iss吗
https://github.com/cyolc932/friends/issues/
我想自己提交也可以 但是怕您哪天换地址了 修改麻烦

**Comment by i-abc** [comment]
> 老哥 您方便提交一下我的友链iss吗 https://github.com/cyolc932/friends/issues/ 我想自己提交也可以 但是怕您哪天换地址了 修改麻烦

好
