### ISSUE TITLE
星辰日记

### ISSUE THREAD

**Issue by i-abc** [i-abc/blog-friends#51]
### 检查清单

- [X] 合法的、无木马植入。
- [X] 有实质性原创内容的个人博客或组织。
- [X] 必须是 HTTPS 站点。
- [X] 关于广告，需合法，且不影响正常阅读。

### 友链信息

```json
{
    "title": "星辰日记",
    "url": "https://blog.xsot.cn",
    "avatar": "https://img.iirose.cn/blog/logo.webp",
    "description": "我们都输给了那伟大的黑色"
}
```

### 友链地址

https://blog.xsot.cn/link

**Comment by soxft** [comment]
大佬怎么自己帮我加上了 😂

**Comment by i-abc** [comment]
> 大佬怎么自己帮我加上了 😂

没事没事，那用你加的那个好了，要改动什么你也方便。
